export const GET_EVENT_LIST_REQUEST = "GET_EVENT_LIST_REQUEST";
export const GET_EVENT_LIST_SUCCESS = "GET_EVENT_LIST_SUCCESS";
export const GET_EVENT_LIST_FAIL = "GET_EVENT_LIST_FAIL";

export const GET_EVENT_LISTBYDAY_REQUEST = "GET_EVENT_LISTBYDAY_REQUEST";
export const GET_EVENT_LISTBYDAY_SUCCESS = "GET_EVENT_LISTBYDAY_SUCCESS";
export const GET_EVENT_LISTBYDAY_FAIL = "GET_EVENT_LISTBYDAY_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const RESET_EVENT_MANAGEMENT = "RESET_EVENT_MANAGEMENT";

export const POST_UPDATE_EVENT_REQUEST = "POST_UPDATE_EVENT_REQUEST";
export const POST_UPDATE_EVENT_SUCCESS = "POST_UPDATE_EVENT_SUCCESS";
export const POST_UPDATE_EVENT_FAIL = "POST_UPDATE_EVENT_FAIL";

export const UPDATE_NONEIMAGE_EVENT_REQUEST = "UPDATE_NONEIMAGE_EVENT_REQUEST";
export const UPDATE_NONEIMAGE_EVENT_SUCCESS = "UPDATE_NONEIMAGE_EVENT_SUCCESS";
export const UPDATE_NONEIMAGE_EVENT_FAIL = "UPDATE_NONEIMAGE_EVENT_FAIL";

export const GET_EVENT_LIST_REQUEST2 = "GET_EVENT_LIST_REQUEST2";
export const GET_EVENT_LIST_SUCCESS2 = "GET_EVENT_LIST_SUCCESS2";
export const GET_EVENT_LIST_FAIL2 = "GET_EVENT_LIST_FAIL2";

export const ADD_EVENT_UPLOAD_REQUEST = "ADD_EVENT_UPLOAD_REQUEST";
export const ADD_EVENT_UPLOAD_SUCCESS = "ADD_EVENT_UPLOAD_SUCCESS";
export const ADD_EVENT_UPLOAD_FAIL = "ADD_EVENT_UPLOAD_FAIL";

export const SAVE_BEFOREINSTALLPROMPT_EVENT = "SAVE_BEFOREINSTALLPROMPT_EVENT"; // Lưu lại event beforeinstallprompt để hiện lại màn hình install pwa khi cần
